[project]
name = "Riddles"
version = "0.1.0"
description = "Solving varouis programming riddles for fun"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.2",
    "requests>=2.32.5",
]

[tool.uv.workspace]
members = [
    "Riddles",
]
